# Site settings
title: NSF BRIDGES, Building Resources for InterDisciplinary training in Genomic and Ecosystem Sciences
email: bridgesNRT@arizona.edu
description: > # this means to ignore newlines until "baseurl:"
   A graduate fellowship and training program at the University of Arizona
#url: "https://ecosystem-genomics.github.io"

# Build settings
markdown: kramdown

assets:
  sources:
    - assets/fonts
    - assets/images
    - assets/js
    - assets/css

gems:
  - jekyll-assets

theme: jekyll-theme-time-machine 
